-- INSTRUCTOR ONLY. Do not distribute to trainees.
-- Instructor account (not touched by environment reset) + scenario catalogue.

do $$
declare iid uuid := md5('nuqta-training:user:instructor')::uuid;
begin
  if not exists (select 1 from auth.users where id = iid) then
    insert into auth.users(instance_id,id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,
      created_at,updated_at,confirmation_token,recovery_token,email_change_token_new,email_change,email_change_token_current,phone_change,phone_change_token,reauthentication_token)
    values ('00000000-0000-0000-0000-000000000000',iid,'authenticated','authenticated','instructor@training.nuqta-demo.test',
      extensions.crypt('Instructor#2026',extensions.gen_salt('bf')),now(),'{"provider":"email","providers":["email"]}','{"full_name":"Training Instructor"}',
      now(),now(),'','','','','','','','');
    insert into auth.identities(id,user_id,provider_id,identity_data,provider,last_sign_in_at,created_at,updated_at)
    values (gen_random_uuid(),iid,iid::text,jsonb_build_object('sub',iid::text,'email','instructor@training.nuqta-demo.test','email_verified',true),'email',now(),now(),now());
    insert into public.profiles(id,email,full_name,title,is_instructor) values (iid,'instructor@training.nuqta-demo.test','Training Instructor','Programme Lead',true);
  end if;
end $$;

insert into public.training_scenarios
(id,title,category,feature,prerequisites,difficulty,severity,expected_secure,flawed_behavior,investigation_path,expected_evidence,business_impact,remediation,chain) values
('S-01','Bootstrap configuration over-disclosure','Information disclosure','App bootstrap / GET /api/v2/meta/config','Any authenticated session','Easy','Low',
 'Bootstrap returns only UI flags needed by the client.','Config also returns the sandbox tenant UUID, a legacy export path and a synthetic signing hint (TRAINING_SECRET_demo_12345).',
 'Observe network calls after login; inspect meta/config response; note tenant id and legacy path.','Response body containing sandboxTenantId and legacyExportPath.',
 'Reveals tenant identifiers and an undocumented endpoint that enables follow-on attacks.','Return only client-required flags; keep tenant identifiers and legacy paths server-side.','CH-A,CH-B'),
('S-02','Document version history without tenant check','IDOR / BOLA','Documents / GET /api/v2/documents/:id/versions','Another org document id','Medium','High',
 'Version history is returned only to members of the owning organization.','Versions endpoint authenticates but does not verify document.org_id against the caller context.',
 'Compare GET /documents/:id (404 cross-tenant) with /documents/:id/versions (200).','Version bodies for a document owned by another organization.',
 'Disclosure of document content across tenants.','Apply the same ownership guard as the parent document route.',NULL),
('S-03','Private AI conversation readable by org peers','Horizontal authorization','Mibyan / GET /api/v2/ai/conversations/:id','Two users in one org','Medium','Medium',
 'Private conversations are readable only by their owner.','Conversation detail checks org membership but not owner/visibility.',
 'Log in as two employees; request a conversation id owned by the other.','Messages of a private conversation returned to a peer.',
 'Leakage of confidential prompts and drafts between colleagues.','Enforce owner or visibility rules on every read.',NULL),
('S-04','Invoice marked Paid by employee','Vertical authorization','Invoices / POST /api/v2/invoices/:id/transition','Employee session','Medium','High',
 'Only managers may approve; only admins may mark Paid.','Transition to Paid only checks organization membership.',
 'Compare transition responses across roles for each target state.','Invoice status Paid set by an employee account.',
 'Fraudulent settlement of invoices.','Role gate every transition server-side using a transition/role matrix.',NULL),
('S-05','Invoice line items across tenants','Cross-tenant authorization','Invoices / GET /api/v2/invoices/:id/items','Foreign invoice id (see chain B)','Medium','High',
 'Line items are returned only for invoices in the caller organization.','Items endpoint filters by invoice id only.',
 'Obtain an invoice id from another tenant and request /items.','Line items and prices for another tenant invoice.',
 'Cross-tenant financial disclosure.','Join to invoices and enforce org_id on child resources.','CH-B'),
('S-06','Customer update accepts ownership fields','Mass assignment','Customers / PATCH /api/v2/customers/:id','Manager or employee session','Medium','High',
 'Only whitelisted business fields are updatable.','Request body is spread into the update, allowing org_id and owner_id changes.',
 'Send extra properties in PATCH and observe the stored record.','Customer moved to another organization via org_id.',
 'Tenant boundary corruption and data exfiltration.','Whitelist properties; reject unknown fields.',NULL),
('S-07','Member removal without role check','Broken function-level authorization','Team / DELETE /api/v2/members/:userId','Employee session','Easy','High',
 'Only organization_admin may remove members.','UI hides the action but the API only checks membership.',
 'Replay an admin removal request from a lower-privileged session.','204 response and member status removed.',
 'Denial of access to legitimate staff.','Enforce function-level role checks server-side.',NULL),
('S-08','Message body rendered as HTML','Stored client-side rendering','Messages / channel feed','Any member','Easy','Medium',
 'Message text is rendered as text.','Feed renders stored body through an HTML sink.','Post markup in a message and view the feed as another user.',
 'Script-capable markup executing in a second session (synthetic).','Session actions performed in victim context.','Render as text or sanitize with an allow-list.',NULL),
('S-09','Search term reflected into page','Reflected client-side rendering','Search / ?q=','Any member','Easy','Medium',
 'Search term is displayed as text.','Empty-state message inserts q as HTML.','Visit /search?q=<markup>.','Markup reflected and interpreted.',
 'Crafted links run script in the victim session.','Escape output; avoid innerHTML.',NULL),
('S-10','File download trusts client-supplied org','File ownership/access','Files / GET /api/v2/files/:id/download?org=','Foreign file id','Medium','High',
 'Ownership is derived from the file record.','Membership check uses the org query parameter supplied by the client.',
 'Request a foreign file id with org= set to your own organization.','Signed URL / content for another tenant file.',
 'Cross-tenant document disclosure.','Derive org from file row; compare with caller memberships.',NULL),
('S-11','Account lookup enumerates users','Authentication workflow weakness','Sign-in / POST /api/v2/auth/lookup','None','Easy','Low',
 'Uniform response regardless of account existence.','Distinct messages and metadata for existing vs unknown accounts.',
 'Submit known and unknown emails and compare.','Differing responses/timing.','Account enumeration aids targeted attacks.','Return generic responses.',NULL),
('S-12','Weak password reset code','Password reset workflow weakness','Forgot password / POST /api/v2/auth/reset','Target email','Medium','Critical',
 'High-entropy single-use token with attempt limits.','4-digit code with no per-code lockout.','Request reset, then iterate codes.',
 'Successful reset with brute-forced code (synthetic accounts).','Account takeover.','Use long random tokens, expiry, lockout.','CH-A'),
('S-13','Session revocation is cosmetic','Session lifecycle','Security / Sessions','Two sessions for one user','Medium','Medium',
 'Revoked sessions lose access immediately.','Revoke only flips a display flag; bearer tokens remain valid.','Revoke a session then reuse its token.',
 'API calls still succeed after revocation.','Stolen tokens remain usable.','Enforce session state on every request.',NULL),
('S-14','Unsigned workspace context token trusted','Unsafe trust in token claims','All v2 / x-workspace-context header','Any session','Hard','High',
 'Role is resolved from the database.','Context token with alg=none is accepted and its role claim trusted for org settings.',
 'Decode context token from /auth/context; modify claims; resend.','Org settings changed with forged role claim.',
 'Privilege escalation.','Verify signatures; never trust client role claims.',NULL),
('S-15','Negative invoice line items','Business logic','Invoices / POST /api/v2/invoices','Manager session','Medium','Medium',
 'Quantities and prices must be positive.','Negative quantity accepted; totals may go negative.','Create invoice with negative quantity.',
 'Invoice with reduced/negative total.','Financial integrity loss.','Validate ranges; recompute server-side.',NULL),
('S-16','Project workflow bypass via PATCH','Workflow bypass','Projects / PATCH /api/v2/projects/:id','Project owner','Medium','Medium',
 'Status changes go through ordered transitions with approvals.','PATCH accepts status directly.','Compare transition endpoint to generic update.',
 'Draft project set to Approved.','Approval controls bypassed.','Block status in generic update.',NULL),
('S-17','Credit applied concurrently','Concurrency / race','Invoices / POST /api/v2/invoices/:id/apply-credit','Manager session','Hard','Medium',
 'Balance deducted atomically.','Read-check-write window allows repeated spend.','Send parallel apply-credit requests.',
 'Credit applied more than balance (synthetic).','Revenue leakage.','Atomic update with conditional check.',NULL),
('S-18','Rate limit inconsistent between versions','Rate-limit inconsistency','Reset flow / v1 vs v2','Target email','Medium','Medium',
 'Same limits on every route version.','v2 limit keys on client-supplied X-Forwarded-For; v1 route has none.','Observe 429 on v2 then test v1/headers.',
 'Unlimited attempts via v1 or header rotation.','Enables brute force.','Central limiter keyed on trusted identity.','CH-A'),
('S-19','Overly permissive CORS on widget endpoint','Controlled CORS demonstration','/api/v2/widget/me','Any session','Medium','Medium',
 'Allow-list of origins.','Origin reflected with credentials allowed.','Send arbitrary Origin header.','ACAO equals attacker origin.',
 'Cross-origin data read.','Static origin allow-list.',NULL),
('S-20','Legacy customers endpoint trusts org parameter','Legacy API authorization difference','/api/v1/customers?org=','Foreign org id','Medium','High',
 'Org resolved from membership like v2.','v1 honours ?org= without membership check and returns expanded related ids.','Diff v1 vs v2 behaviour.',
 'Customer list and invoice ids for another tenant.','Cross-tenant disclosure.','Retire v1 or apply v2 guards.','CH-B'),
('S-21','Undocumented legacy member export','Hidden API route','/api/v1/export/members?org=','Path from S-01','Medium','High',
 'Export restricted to org admins of that org.','Any authenticated user may export any org.','Follow legacyExportPath from config.',
 'Member ids, emails, roles and notes for another org.','Identity disclosure for targeting.','Remove route or enforce admin+tenant.','CH-A'),
('S-22','Invitation tokens exposed to all members','Excessive data exposure','Invitations / GET /api/v2/invitations','Employee session','Easy','High',
 'Tokens never returned after creation.','List returns raw tokens to any member.','Inspect invitation list response.','Valid pending tokens visible.',
 'Allows hijacking of invites.','Hash tokens; hide from list.','CH-D'),
('S-23','Invitation acceptance trusts client role','Unsafe client-controlled properties','POST /api/v2/invitations/accept','Token from S-22','Medium','Critical',
 'Role taken from the invitation record.','Body role overrides invitation role.','Accept with role=organization_admin.','New account is organization_admin.',
 'Privilege escalation.','Ignore client role.','CH-D'),
('S-24','Attachments bucket publicly listable','Storage access-control','Storage / attachments bucket','Anon key from client','Medium','High',
 'Private by default; org-scoped read.','Bucket public with broad read policy.','List objects in attachments bucket.','Synthetic export file retrievable anonymously.',
 'Data disclosure.','Make private; org-scoped policies.',NULL),
('S-25','Shared conversation exposes metadata','Excessive data exposure','Mibyan / GET /api/v2/ai/shared/:token','Shared link','Medium','Medium',
 'Shared view shows only messages.','Response includes citations with knowledge document ids and owner email.','Open a shared link and read raw JSON.',
 'Knowledge document id in response.','Reveals identifiers of restricted resources.','Strip internal metadata.','CH-C'),
('S-26','Restricted knowledge document readable by id','Incorrect document authorization','Knowledge / GET /api/v2/knowledge/documents/:id','Document id from S-25','Medium','High',
 'Restricted collections limited to managers.','Detail route skips collection visibility check (list enforces it).','Request id as employee.','Restricted document content returned.',
 'Disclosure of restricted references.','Check parent collection visibility.','CH-C')
on conflict (id) do nothing;
